GET http://localhost:3000/user-api/users

### create the users
POST http://localhost:3000/user-api/users
Content-Type: application/json

{
    "id":100,
    "name":"spr",
    "age":21
}

###
PUT http://localhost:3000/user-api/users
Content-Type:application/json

{
    "id":100,
    "name":"spr",
    "age":30
}

###
GET http://localhost:3000/user-api/users/100

### deleting the users by id
DELETE  http://localhost:3000/user-api/users/100


###products API
GET http://localhost:3000/product-api/products

###
POST http://localhost:3000/product-api/products
Content-Type: application/json

{
    "productId":100,
    "name":"phone",
    "price":1200,
    "brand":"nokia"
}

### products by id
GET http://localhost:3000/product-api/products-id/100

###products by name
GET http://localhost:3000/product-api/products-name/phone


###editing
PUT http://localhost:3000/product-api/products/100
Content-Type:application/json

{
    "productId":101,
    "name":"AC",
    "price":50000,
    "brand":"haier"
}


###delete products
DELETE  http://localhost:3000/product-api/products/100
